# Configurations options https://github.com/robvanderleek/create-issue-branch#configuration

mode: chatops
experimental:
  branchNameArgument: true
gitSafeReplacementChar: '-'

branchName: short

openDraftPR: true
commentMessage: 'Branch ${branchName} created for issue: ${issue.title}'

copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true

autoCloseIssue: true
