name: "\U0001F195 Solicitação de Funcionalidade"
description: "Template para abertura de issue referentes a novas funcionalidades no sistema"
labels: [Funcionalidade]
body:
- type: markdown
  attributes:
    value: |
      Coloque um título acima que descreva de forma resumida a funcionalidade desejada.

      Para facilitar nosso entendimento da mudança precisamos de mais algumas informações.

      ---
- type: textarea
  attributes:
    label: Qual o problema a ser resolvido?
    description: |
      Descreva o problema que deseja resolver com a nova funcionalidade.
  validations:
    required: true
- type: textarea
  attributes:
    label: Quais restrições e regras devem ser observadas?
    description: |
      Informe aqui todas as regras de negócio que devem ser consideradas na implementação.
  validations:
    required: true
- type: textarea
  attributes:
    label: Especificação
    description: |
      Itens da especificação da mudança
    value: |
      - Solução proposta
      - Jornada do usuário
      - Regras de negócio e validações
      - Protótipo
      - Impactos identificados
      - Cenários de testes de integração
      - Planejamento de tarefas
  validations:
    required: false
- type: textarea
  attributes:
    label: Lista de verificação de conclusão
    description: |
      Itens da lista de definição de pronto
    value: |
      - [ ] A solução implementada está de acordo com a solução aprovada
      - [ ] Todos os cenários de teste definidos foram implementados
      - [ ] Testes unitários cobrindo as regras de negócio e validações definidas na especificação
      - [ ] Todas as tarefas do planejamento foram realizadas
  validations:
    required: true