name: "\U0001F6E0 Solicitação de Melhoria"
description: "Template para abertura de issue referentes a melhorias no sistema"
labels: [Melhoria]
body:
- type: markdown
  attributes:
    value: |
      Coloque um título acima que descreva de forma resumida a melhoria desejada.

      Para facilitar nosso entendimento da mudança precisamos de mais algumas informações.

      ---
- type: textarea
  attributes:
    label: Qual o problema a ser resolvido?
    description: |
      Descreva o problema que deseja resolver com a melhorias.
  validations:
    required: true
- type: textarea
  attributes:
    label: Quais restrições e regras devem ser observadas?
    description: |
      Informe aqui todas as regras de negócio que devem ser consideradas na implementação.
  validations:
    required: true


- type: textarea
  attributes:
    label: Especificação
    description: |
      Itens da especificação da mudança
    value: |
      #### Solução proposta
      #### Regras de negócio e validações
      #### Impactos identificados
      #### Cenários de testes
      #### Planejamento de tarefas
  validations:
    required: false

- type: textarea
  attributes:
    label: Definição de preparado
    description: |
      Itens da lista de definição de preparado para desenvolvimento
    value: |
      - [ ] Critério de aceite definido
      - [ ] Todos os insumos necessários para desenvolvimento presentes
      - [ ] Cenários de testes definidos
      - [ ] Tempo estimado
  validations:
    required: true

- type: textarea
  attributes:
    label: Definição de pronto
    description: |
      Itens da lista de definição de pronto
    value: |
      - [ ] A especificação foi atendida
      - [ ] Todos os cenários de teste definidos foram implementados
      - [ ] Testes unitários cobrindo as regras de negócio e validações definidas na especificação
      - [ ] Todas as tarefas do planejamento foram realizadas
  validations:
    required: true
