name: "\U0001F4DE Registro de Suporte"
description: Alteração de dados por falta de funcionalidade, relatórios, reprocessamentos.
labels: [Suporte]
body:
- type: markdown
  attributes:
    value: |
      Coloque um título acima que descreva resumidamente o suporte a ser realizada.

      ---
- type: textarea
  attributes:
    label: Qual o problema a ser resolvido?
    description: |
      Descreva o problema detalhando o máximo que puder.
    placeholder: |
      Exemplo: Alterar a data de solicitação preenchida errada pela Singular.
  validations:
    required: true
- type: textarea
  attributes:
    label: Especificação
    description: |
      Itens da especificação do suporte
    value: |
      #### Detalhamento 
      #### Impactos identificados
      #### Cenários de testes
      #### Planejamento de tarefas
  validations:
    required: false
- type: textarea
  attributes:
    label: Definição de preparado
    description: |
      Itens da lista de definição de pronto
    value: |
      - [ ] Todos os insumos necessários para desenvolvimento presentes
      - [ ] Cenários de testes definidos
      - [ ] Tempo estimado a demanda para isso
  validations:
    required: true
- type: textarea
  attributes:
    label: Definição de pronto
    description: |
      Itens da lista de definição de pronto
    value: |
      - [ ] Verificado se a especificação foi atendida
      - [ ] Verificado a necessidade de criação ou atualização de um procedimento para atendimento de problemas do mesmo tipo no futuro
      - [ ] Verificado se existem outros casos da mesma natureza do problema atendido e se foi dada uma tratativa
      - [ ] Verificado a causa raiz do problema e se o mesmo foi corrigido ou registrado um defeito para correção
  validations:
    required: true
