name: "\U0001F6E0 Registro de Tarefa"
description: Tarefas internas de manutenção, implementação de testes e outros.
labels: [Tarefa]
body:
- type: markdown
  attributes:
    value: |
      Coloque um título acima que descreva resumidamente a tarefa a ser realizada.

      ---
- type: textarea
  attributes:
    label: Qual a tarefa a ser realizada?
    description: |
      Descreva a tarefa detalhando o máximo que puder.
    placeholder: |
      Exemplo: Ao clicar no botão "Salvar" o sistema apresenta uma mensagem de erro.
  validations:
    required: true
- type: textarea
  attributes:
    label: Informações adicionais sobre a tarefa
    description: |
      Se possível, adicione uma captura de tela.
    placeholder: |
      Exemplo: Maiores informações sobre a tarefa
  validations:
    required: false
- type: textarea
  attributes:
    label: Lista de verificação de conclusão
    description: |
      Itens da lista de definição de pronto
    value: |
      - [ ] Verificado a necessidade de criação ou atualização de um procedimento para atendimento de tarefas do mesmo tipo no futuro
  validations:
    required: true